name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.160.0"
          extended: true

      - name: Install geekdoc theme
        run: |
          mkdir -p themes/hugo-geekdoc
          curl -sL https://github.com/thegeeklab/hugo-geekdoc/releases/download/v3.0.0/hugo-geekdoc.tar.gz | tar xz -C themes/hugo-geekdoc

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ github.token }}
          external_repository: rdkit-rs/rdkit-rs.github.io
          publish_dir: ./public
          publish_branch: gh-pages
